name: Checks

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: "19.0.0"
          cache: npm
      - run: npm install
      - run: make lint
    timeout-minutes: 5
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: "19.0.0"
          cache: npm
      - run: npm install
      - run: make format-check
    timeout-minutes: 5
